"""
Centralized Prometheus metrics for the Amael-IA agent layer.
Import from here in planner.py, executor.py, and orchestrator.py.
"""
from prometheus_client import Counter, Histogram, Gauge

# ── Planner ──────────────────────────────────────────────────────────────────
PLANNER_LATENCY_SECONDS = Histogram(
    "amael_planner_latency_seconds",
    "LLM call latency for plan generation",
    buckets=(0.5, 1, 2, 4, 8, 15, 30),
)
PLANNER_PLAN_SIZE = Histogram(
    "amael_planner_plan_size_steps",
    "Number of steps in the generated plan",
    buckets=(1, 2, 3, 4, 5, 6, 7, 8),
)
PLANNER_STEP_TYPES_TOTAL = Counter(
    "amael_planner_step_types_total",
    "Count of each step type generated by the planner",
    ["step_type"],
)
PLANNER_PARSE_ERRORS_TOTAL = Counter(
    "amael_planner_parse_errors_total",
    "JSON parse failures in planner output",
)
PLANNER_INVALID_STEPS_TOTAL = Counter(
    "amael_planner_invalid_steps_total",
    "Steps with unrecognised type discarded by _validate_plan",
)

# ── Executor ──────────────────────────────────────────────────────────────────
EXECUTOR_STEP_LATENCY_SECONDS = Histogram(
    "amael_executor_step_latency_seconds",
    "Wall-clock latency per executed plan step",
    ["step_type"],
    buckets=(0.1, 0.5, 1, 2, 5, 10, 30, 60, 120),
)
EXECUTOR_STEPS_TOTAL = Counter(
    "amael_executor_steps_total",
    "Total plan steps executed",
    ["step_type"],
)
EXECUTOR_ERRORS_TOTAL = Counter(
    "amael_executor_errors_total",
    "Executor step failures (missing tool, exception, etc.)",
    ["step_type"],
)
EXECUTOR_CONTEXT_TRUNCATIONS_TOTAL = Counter(
    "amael_executor_context_truncations_total",
    "Number of times the accumulated context was truncated to fit the LLM window",
)
EXECUTOR_ESTIMATED_PROMPT_TOKENS = Histogram(
    "amael_executor_estimated_prompt_tokens",
    "Estimated token count sent to LLM per REASONING step (chars / 4)",
    ["step_type"],
    buckets=(100, 500, 1000, 2000, 4000, 8000, 16000, 32000),
)

# ── Orchestrator ──────────────────────────────────────────────────────────────
ORCHESTRATOR_MAX_STEPS_HIT_TOTAL = Counter(
    "amael_orchestrator_max_steps_hit_total",
    "Number of times MAX_GRAPH_ITERATIONS was reached before plan completed",
)

# ── Parallel execution ────────────────────────────────────────────────────────
EXECUTOR_PARALLEL_BATCH_SIZE = Histogram(
    "amael_executor_parallel_batch_size",
    "Number of steps executed in a single parallel batch (>1 means real parallelism)",
    buckets=(1, 2, 3, 4, 5, 6),
)
EXECUTOR_PARALLEL_BATCHES_TOTAL = Counter(
    "amael_executor_parallel_batches_total",
    "Number of batches executed with more than one step in parallel",
)

# ── Supervisor (P3) ───────────────────────────────────────────────────────────
SUPERVISOR_DECISIONS_TOTAL = Counter(
    "amael_supervisor_decisions_total",
    "Total supervisor decisions by outcome",
    ["decision"],   # ACCEPT | REPLAN
)
SUPERVISOR_QUALITY_SCORE = Histogram(
    "amael_supervisor_quality_score",
    "Quality score (0-10) assigned by the supervisor to the final answer",
    buckets=(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
)
SUPERVISOR_REPLAN_TOTAL = Counter(
    "amael_supervisor_replan_total",
    "Number of times the supervisor triggered a re-plan",
)
SUPERVISOR_LATENCY_SECONDS = Histogram(
    "amael_supervisor_latency_seconds",
    "LLM call latency for supervisor evaluation",
    buckets=(0.5, 1, 2, 4, 8, 15, 30),
)
