apiVersion: v1
kind: ConfigMap
metadata:
  name: allowed-users-configmap
  namespace: amael-ia
data:
  ALLOWED_EMAILS_CSV: "lucero.ahumada26@gmail.com,ricardogs26@gmail.com,rguzmans@bancobase.com,admin@gmail.com,test@example.com,bot-amael@richardx.dev"
  # Lista estricta. Solo estos podrán listar pods, borrar deployments, etc. (Puede incluir números de WA)
  K8S_ALLOWED_USERS_CSV: "ricardogs26@gmail.com,rguzmans@bancobase.com,bot-amael@richardx.dev"
