apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-service-deployment
  namespace: amael-ia
  labels:
    app: productivity-service
spec:
  replicas: 1  # Puedes aumentar esto si necesitas más disponibilidad
  selector:
    matchLabels:
      app: productivity-service
  template:
    metadata:
      labels:
        app: productivity-service
    spec:
      serviceAccountName: productivity-service-sa
      containers:
      - name: productivity-service
        image: registry.richardx.dev/productivity-service:1.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        env:
        - name: VAULT_ADDR
          value: "http://vault.vault.svc.cluster.local:8200"
        - name: VAULT_ROLE
          value: "amael-productivity"
        envFrom:
        - configMapRef:
            name: productivity-service-config
        - secretRef:
            name: productivity-service-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 5
          periodSeconds: 10