apiVersion: v1
kind: Secret
metadata:
  name: k8s-agent-secret
  namespace: amael-ia
type: Opaque
stringData:
  new_relic_account_id: "TU_ACCOUNT_ID"
  new_relic_api_key: "TU_API_KEY_AQUI"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-agent-configmap
  namespace: amael-ia
data:
  OLLAMA_BASE_URL: "http://ollama-service:11434"
  MODEL_NAME: "glm4"
