apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../07.-whatsapp-pvc.yaml
- ../../08.-whatsapp-deployment.yaml
images:
- name: registry.richardx.dev/whatsapp-bridge
  newTag: 1.5.7
